apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: chattingo-alerts
  namespace: monitoring
  labels:
    app: chattingo
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: chattingo.rules
    rules:
    - alert: ChattingoBackendDown
      expr: up{job="chattingo-backend"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Chattingo Backend is down"
        description: "Chattingo backend has been down for more than 1 minute."

    - alert: ChattingoFrontendDown
      expr: up{job="chattingo-frontend"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Chattingo Frontend is down"
        description: "Chattingo frontend has been down for more than 1 minute."

    - alert: ChattingoPodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{namespace="default",pod=~"chattingo-.*"}[5m]) > 0
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Chattingo pod is crash looping"
        description: "Pod {{ $labels.pod }} is restarting frequently."

    - alert: ChattingoHighMemoryUsage
      expr: (container_memory_usage_bytes{namespace="default",pod=~"chattingo-.*"} / container_spec_memory_limit_bytes) * 100 > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage in Chattingo"
        description: "Memory usage is above 80% for pod {{ $labels.pod }}."

    - alert: ChattingoHighCPUUsage
      expr: (rate(container_cpu_usage_seconds_total{namespace="default",pod=~"chattingo-.*"}[5m]) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage in Chattingo"
        description: "CPU usage is above 80% for pod {{ $labels.pod }}."

    - alert: ChattingoMySQLDown
      expr: up{job="chattingo-mysql"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Chattingo MySQL is down"
        description: "MySQL database for Chattingo has been down for more than 1 minute."
